// Generated by npm run build:codex. Includes MIT-licensed Langfuse rollout parsing; see ../vendor/LICENSE and ../UPSTREAM.md.

// plugins/codex-langfuse/scripts/hook.mjs
import { readFile, readdir } from "node:fs/promises";
import { mkdirSync as mkdirSync2, writeFileSync as writeFileSync2 } from "node:fs";
import { join as join3, dirname as dirname3, resolve as resolve2, basename } from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath as fileURLToPath3 } from "node:url";
import { setTimeout as delay } from "node:timers/promises";

// plugins/codex-langfuse/vendor/utils.ts
function isPrimitive(value) {
  const t = typeof value;
  return t === "string" || t === "number" || t === "boolean";
}
function toText(value) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (isPrimitive(value)) return String(value);
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

// plugins/codex-langfuse/vendor/parse.ts
function extractMessageText(content) {
  if (!Array.isArray(content)) return "";
  return content.map((part) => {
    if (!part || typeof part !== "object") return "";
    if (part.type === "input_text" || part.type === "output_text" || part.type === "text") {
      return typeof part.text === "string" ? part.text : "";
    }
    return "";
  }).filter(Boolean).join("\n");
}
function extractReasoning(item) {
  if (typeof item.content === "string") return item.content;
  if (Array.isArray(item.content)) {
    return item.content.map(
      (c) => c && typeof c === "object" && "text" in c ? toText(c.text) : toText(c)
    ).filter(Boolean).join("\n");
  }
  if (Array.isArray(item.summary) && item.summary.length > 0) {
    return item.summary.map((s) => toText(s)).filter(Boolean).join("\n");
  }
  return "";
}
function parseArgs(raw) {
  if (typeof raw !== "string") return raw;
  try {
    return JSON.parse(raw);
  } catch {
    return raw;
  }
}
function extractToolError(payload) {
  const explicit = payload.error ?? payload.codex_error_info;
  if (explicit != null) {
    return isPrimitive(explicit) ? String(explicit) : JSON.stringify(explicit);
  }
  const streams = [payload.stdout, payload.stderr].filter((s) => typeof s === "string" && s.length > 0).join("\n");
  if (typeof payload.aggregated_output === "string" && payload.aggregated_output) {
    return payload.aggregated_output;
  }
  if (streams) return streams;
  if (typeof payload.exit_code === "number") return `Exit code: ${payload.exit_code}`;
  return void 0;
}
function newTurn(startTime) {
  return {
    turnId: void 0,
    startTime,
    endTime: startTime,
    steps: [],
    subagentThreadIds: [],
    completed: false,
    aborted: false
  };
}
function parseSession(lines) {
  let sessionMeta = { sessionId: "unknown" };
  const turns = [];
  let turn = null;
  let step = null;
  let toolCallsById = /* @__PURE__ */ new Map();
  let lastTimestamp = Date.now();
  function newStep(startTime) {
    return { startTime, endTime: startTime, toolCalls: [] };
  }
  const ensureTurn = (ts) => turn ??= newTurn(ts);
  const ensureStep = (ts) => step ??= newStep(ts);
  const recordSubagentThread = (threadId) => {
    if (!turn.subagentThreadIds.includes(threadId)) {
      turn.subagentThreadIds.push(threadId);
    }
  };
  const closeStep = (ts, usage) => {
    if (!step) return;
    step.endTime = Math.max(step.endTime, ts);
    if (usage) step.usage = usage;
    turn.steps.push(step);
    step = null;
  };
  const finishTurn = (ts, opts) => {
    if (!turn) return;
    closeStep(ts);
    turn.endTime = Math.max(turn.endTime, ts);
    turn.completed = opts.completed;
    turn.aborted = opts.aborted;
    turn.userInput = turn.userInput ?? turn.userInputFallback;
    turn.finalOutput = turn.lastAgentMessage ?? turn.steps.filter((s) => s.text).at(-1)?.text;
    delete turn.lastAgentMessage;
    delete turn.userInputFallback;
    turns.push(turn);
    turn = null;
    toolCallsById = /* @__PURE__ */ new Map();
  };
  for (const line of lines) {
    const ts = Number.isFinite(Date.parse(line.timestamp)) ? Date.parse(line.timestamp) : lastTimestamp;
    lastTimestamp = ts;
    if (line.type === "session_meta") {
      const p = line.payload;
      sessionMeta = {
        sessionId: typeof p.id === "string" ? p.id : sessionMeta.sessionId,
        cliVersion: p.cli_version,
        modelProvider: p.model_provider ?? void 0,
        baseInstructions: p.base_instructions?.text,
        isSubagentThread: typeof p.parent_thread_id === "string" || p.thread_source === "subagent"
      };
      continue;
    }
    if (line.type === "turn_context") {
      const t = ensureTurn(ts);
      const p = line.payload;
      t.model = p.model ?? t.model;
      t.invocationParams = line.payload;
      continue;
    }
    if (line.type === "response_item") {
      const p = line.payload;
      ensureTurn(ts);
      if (p.type === "message") {
        const msg = p;
        const text = extractMessageText(msg.content);
        if (msg.role === "assistant") {
          const s = ensureStep(ts);
          if (text) s.text = s.text ? `${s.text}
${text}` : text;
        } else if (msg.role === "user" && text) {
          if (!turn.userInputFallback && !/<\/?(environment_context|user_instructions)\b/.test(text) && !/^# AGENTS\.md instructions for\b/.test(text.trim())) {
            turn.userInputFallback = text;
          }
        }
      } else if (p.type === "function_call") {
        const call = p;
        const s = ensureStep(ts);
        const tc = {
          callId: call.call_id,
          name: call.name,
          args: parseArgs(call.arguments),
          startTime: ts
        };
        s.toolCalls.push(tc);
        toolCallsById.set(tc.callId, tc);
      } else if (p.type === "custom_tool_call") {
        const call = p;
        const s = ensureStep(ts);
        const tc = {
          callId: call.call_id,
          name: call.name,
          args: parseArgs(call.input),
          startTime: ts
        };
        s.toolCalls.push(tc);
        toolCallsById.set(tc.callId, tc);
      } else if (p.type === "local_shell_call") {
        const call = p;
        const s = ensureStep(ts);
        const tc = {
          callId: call.call_id ?? call.id ?? `local_shell_${ts}_${s.toolCalls.length}`,
          name: "local_shell",
          args: call.action ?? void 0,
          startTime: ts
        };
        s.toolCalls.push(tc);
        toolCallsById.set(tc.callId, tc);
      } else if (p.type === "web_search_call") {
        const call = p;
        const callId = call.id ?? `web_search_${ts}`;
        const existing = toolCallsById.get(callId);
        if (existing) {
          existing.args = existing.args ?? call.action ?? void 0;
          existing.endTime = Math.max(existing.endTime ?? ts, ts);
        } else {
          const s = ensureStep(ts);
          const tc = {
            callId,
            name: "web_search",
            args: call.action ?? void 0,
            startTime: ts
          };
          s.toolCalls.push(tc);
          toolCallsById.set(callId, tc);
        }
      } else if (p.type === "function_call_output" || p.type === "custom_tool_call_output") {
        const out = p;
        const tc = toolCallsById.get(out.call_id);
        if (tc) {
          if (tc.output == null) tc.output = out.output;
          tc.endTime = Math.max(tc.endTime ?? ts, ts);
        }
      } else if (p.type === "reasoning") {
        const reasoning = extractReasoning(
          p
        );
        if (reasoning) {
          const s = ensureStep(ts);
          s.reasoning = s.reasoning ? `${s.reasoning}
${reasoning}` : reasoning;
        }
      }
      continue;
    }
    if (line.type === "event_msg") {
      const p = line.payload;
      const et = p.type;
      if (et === "task_started") {
        if (turn) finishTurn(ts, { completed: false, aborted: false });
        turn = newTurn(ts);
        turn.turnId = typeof p.turn_id === "string" ? p.turn_id : void 0;
        continue;
      }
      ensureTurn(ts);
      if (et === "user_message" && typeof p.message === "string") {
        if (!turn.userInput) turn.userInput = p.message;
      } else if (et === "item_completed" && p.item?.type === "UserMessage") {
        const text = extractMessageText(p.item.content);
        if (text && !turn.userInput) turn.userInput = text;
      } else if (et === "agent_message" && typeof p.message === "string") {
        turn.lastAgentMessage = p.message;
      } else if (et === "token_count") {
        if (p.info?.total_token_usage) turn.totalUsage = p.info.total_token_usage;
        closeStep(ts, p.info?.last_token_usage ?? void 0);
      } else if (et === "task_complete") {
        finishTurn(ts, { completed: true, aborted: false });
      } else if (et === "turn_aborted") {
        finishTurn(ts, { completed: true, aborted: true });
      } else {
        if (et === "collab_agent_spawn_end" && typeof p.new_thread_id === "string") {
          recordSubagentThread(p.new_thread_id);
        }
        if (et === "sub_agent_activity" && p.kind === "started" && typeof p.agent_thread_id === "string") {
          recordSubagentThread(p.agent_thread_id);
        }
        if ((et === "mcp_tool_call_begin" || et === "mcp_tool_call_end") && typeof p.call_id === "string") {
          const tc = toolCallsById.get(p.call_id);
          const inv = p.invocation;
          if (tc && typeof inv?.server === "string" && typeof inv?.tool === "string") {
            tc.mcp = { server: inv.server, tool: inv.tool };
          }
        }
        if (et === "web_search_end" && typeof p.call_id === "string") {
          let tc = toolCallsById.get(p.call_id);
          if (!tc) {
            tc = { callId: p.call_id, name: "web_search", args: void 0, startTime: ts };
            ensureStep(ts).toolCalls.push(tc);
            toolCallsById.set(tc.callId, tc);
          }
          tc.args = tc.args ?? p.action ?? (typeof p.query === "string" ? { query: p.query } : void 0);
        }
        if (typeof p.call_id === "string" && et.endsWith("_end")) {
          const tc = toolCallsById.get(p.call_id);
          if (tc) {
            tc.endTime = Math.max(tc.endTime ?? ts, ts);
            if (p.status === "failed" || p.status === "declined") {
              tc.error = extractToolError(p);
            }
            if (tc.output == null) {
              tc.output = p.aggregated_output ?? p.stdout ?? p.result;
            }
          }
        }
      }
      continue;
    }
  }
  if (turn) finishTurn(lastTimestamp, { completed: false, aborted: false });
  return { sessionMeta, turns };
}

// scripts/profiles.mjs
import { readFileSync, mkdirSync, writeFileSync, renameSync, rmSync } from "node:fs";
import { join as join2, dirname as dirname2, isAbsolute as isAbsolute2 } from "node:path";
import { homedir as homedir2 } from "node:os";
import { createHash, randomUUID } from "node:crypto";

// scripts/settings.mjs
import { dirname, resolve, join, isAbsolute } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
var projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
var workbuddyHome = process.env.WORKBUDDY_CONFIG_DIR || process.env.CODEBUDDY_CONFIG_DIR || join(homedir(), ".workbuddy");
var configPath = process.env.WORKBUDDY_LANGFUSE_CONFIG || join(workbuddyHome, "langfuse.json");
var pluginHome = join(workbuddyHome, "langfuse-plugin");
var defaults = { content: "metadata", maxContentChars: 16e3, stalledAfterSeconds: 60, pollIntervalMs: 1e3, prices: {} };
function validateSettings(settings) {
  if (!["metadata", "text"].includes(settings.content)) throw new Error("content must be metadata or text");
  if (!Number.isInteger(settings.maxContentChars) || settings.maxContentChars < 100 || settings.maxContentChars > 64e3) throw new Error("maxContentChars must be 100\u201364000");
  if (!Number.isInteger(settings.stalledAfterSeconds) || settings.stalledAfterSeconds < 5) throw new Error("stalledAfterSeconds must be at least 5");
  if (!Number.isInteger(settings.pollIntervalMs) || settings.pollIntervalMs < 500) throw new Error("pollIntervalMs must be at least 500");
  if (!settings.prices || typeof settings.prices !== "object" || Array.isArray(settings.prices)) throw new Error("prices must be an object");
  return settings;
}
function validateConfig(config) {
  validateSettings(config);
  if (typeof config.enabled !== "boolean") throw new Error("enabled must be true or false");
  let url;
  try {
    url = new URL(config.base_url);
  } catch {
    throw new Error("Invalid Langfuse URL");
  }
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.search || url.hash || url.pathname !== "/") {
    throw new Error("Use the Langfuse base URL without /api, project paths, credentials, query parameters or fragments");
  }
  for (const key of ["public_key", "secret_key"]) {
    if (typeof config[key] !== "string" || config[key] && !/^[A-Za-z0-9_-]+$/.test(config[key])) throw new Error(`${key} has an invalid format`);
  }
  for (const key of ["organization_name", "project_name"]) {
    if (typeof config[key] !== "string" || !config[key].trim() || /[\x00-\x1f\x7f]/.test(config[key])) throw new Error(`${key} must be a non-empty name`);
  }
  if (config.data_directory && (typeof config.data_directory !== "string" || !isAbsolute(config.data_directory))) throw new Error("data_directory must be an absolute path");
  return { ...config, base_url: url.origin };
}

// scripts/profiles.mjs
var helperHome = () => {
  const directory = process.env.LANGFUSE_HELPER_HOME || join2(homedir2(), ".langfuse-helper");
  if (!isAbsolute2(directory)) throw new Error("LANGFUSE_HELPER_HOME must be an absolute path.");
  return directory;
};
var profilePath = () => join2(helperHome(), "config.json");
var digest = (value) => createHash("sha256").update(value).digest("hex");
function readJson(file, fallback) {
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return fallback;
    throw new Error(`Could not read JSON: ${file}`);
  }
}
function saveJson(file, value) {
  mkdirSync(dirname2(file), { recursive: true, mode: 448 });
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporary, JSON.stringify(value, null, 2) + "\n", { mode: 384, flag: "wx" });
    renameSync(temporary, file);
  } finally {
    rmSync(temporary, { force: true });
  }
}
function readProfiles() {
  const config = readJson(profilePath(), { version: 1, targets: {}, agents: {} });
  if (config?.version !== 1 || !config.targets || !config.agents || Array.isArray(config.targets) || Array.isArray(config.agents)) throw new Error("Invalid helper configuration. Expected version 1, targets and agents.");
  return config;
}
function resolveAgent(agent, config = readProfiles()) {
  const binding = config.agents[agent];
  const target = binding && config.targets[binding.target];
  if (!target || !target.project_id) throw new Error(`No verified target. Run langfuse-helper ${agent} configure.`);
  const settings = validateConfig({ ...defaults, organization_name: "Personal", ...binding, ...target });
  const identity = `${settings.base_url}/${target.project_id}`;
  return {
    ...settings,
    targetName: binding.target,
    identity,
    data_directory: join2(helperHome(), "state", agent, digest(identity))
  };
}

// scripts/delivery.mjs
import { DatabaseSync } from "node:sqlite";
var spanOf = (batch) => batch.resourceSpans[0].scopeSpans[0].spans[0];
var DeliveryLedger = class {
  constructor(path, target) {
    this.db = new DatabaseSync(path);
    this.target = target;
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;
      CREATE TABLE IF NOT EXISTS deliveries (target TEXT, identity TEXT, digest TEXT, status TEXT,
        PRIMARY KEY(target, identity));`);
    const columns = new Set(this.db.prepare("PRAGMA table_info(deliveries)").all().map((row) => row.name));
    if (!columns.has("payload")) this.db.exec("ALTER TABLE deliveries ADD COLUMN payload TEXT");
    if (!columns.has("updated_at")) this.db.exec("ALTER TABLE deliveries ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0");
  }
  pending(records) {
    return records.filter((record) => {
      const previous = this.db.prepare("SELECT digest, status FROM deliveries WHERE target = ? AND identity = ?").get(this.target, record.key);
      if (!previous) return true;
      if (previous.digest !== record.digest) throw new Error("Registered span content changed; remote records cannot be overwritten.");
      if (previous.status === "sending" || previous.status === "uncertain") throw new Error("Previous delivery is uncertain. Check Langfuse before retrying; automatic replay is blocked.");
      return previous.status !== "accepted";
    });
  }
  reserve(records) {
    this.db.exec("BEGIN IMMEDIATE");
    try {
      const pending = this.pending(records);
      for (const record of pending) this.db.prepare(`INSERT INTO deliveries(target, identity, digest, status, payload, updated_at) VALUES (?, ?, ?, 'sending', ?, ?)
        ON CONFLICT(target, identity) DO UPDATE SET status = 'sending', payload = excluded.payload, updated_at = excluded.updated_at`).run(this.target, record.key, record.digest, JSON.stringify(record.payload), Date.now());
      this.db.exec("COMMIT");
      return pending;
    } catch (error) {
      this.db.exec("ROLLBACK");
      throw error;
    }
  }
  finish(records, status) {
    this.db.exec("BEGIN IMMEDIATE");
    try {
      for (const record of records) this.db.prepare("UPDATE deliveries SET status = ?, updated_at = ? WHERE target = ? AND identity = ?").run(status, Date.now(), this.target, record.key);
      this.db.exec("COMMIT");
    } catch (error) {
      this.db.exec("ROLLBACK");
      throw error;
    }
  }
  uncertain() {
    return this.db.prepare("SELECT * FROM deliveries WHERE target = ? AND status IN ('sending', 'uncertain')").all(this.target);
  }
  status(key) {
    return this.db.prepare("SELECT status, digest FROM deliveries WHERE target = ? AND identity = ?").get(this.target, key);
  }
  counts() {
    return Object.fromEntries(this.db.prepare("SELECT status, count(*) AS count FROM deliveries WHERE target = ? GROUP BY status").all(this.target).map((row) => [row.status, row.count]));
  }
  close() {
    this.db.close();
  }
};
async function sendRecords(records, ledger, request) {
  const pending = ledger.pending(records);
  if (!pending.length) return 0;
  const body = JSON.stringify({ resourceSpans: pending.flatMap((record) => record.payload.resourceSpans) });
  if (pending.length > 1e3 || Buffer.byteLength(body) > 4 * 1024 * 1024) throw new Error("A manual batch supports at most 1000 spans and 4 MiB. Nothing was sent.");
  const reserved = ledger.reserve(pending);
  if (!reserved.length) return 0;
  const reservedBody = JSON.stringify({ resourceSpans: reserved.flatMap((record) => {
    const payload = structuredClone(record.payload);
    spanOf(payload).attributes.push({ key: "langfuse.observation.metadata.deliveryDigest", value: { stringValue: record.digest } });
    return payload.resourceSpans;
  }) });
  let response;
  try {
    response = await request(reservedBody);
  } catch (error) {
    const unsent = ["ECONNREFUSED", "ENOTFOUND", "EAI_AGAIN"].includes(error.cause?.code || error.code);
    ledger.finish(reserved, unsent ? "rejected" : "uncertain");
    throw new Error(unsent ? "Connection was not established. Records are retained for retry." : "Network response is uncertain. Automatic replay is blocked; check remote records first.");
  }
  if (!response.ok) {
    ledger.finish(reserved, [400, 401, 403, 404, 413, 415].includes(response.status) ? "rejected" : "uncertain");
    throw new Error(`Langfuse returned HTTP ${response.status}; delivery state was retained.`);
  }
  try {
    const result = await response.json();
    if (Number(result.partialSuccess?.rejectedSpans || 0) > 0) throw new Error("partial rejection");
  } catch {
    ledger.finish(reserved, "uncertain");
    throw new Error("Langfuse response did not fully confirm acceptance; automatic replay is blocked.");
  }
  ledger.finish(reserved, "accepted");
  return reserved.length;
}
function langfuseConfig(config) {
  const baseUrl = new URL(config.base_url);
  if (!config.public_key || !config.secret_key) throw new Error("Project API keys are missing. Run langfuse-helper <agent> configure.");
  const base = baseUrl.href.replace(/\/$/, "");
  const auth = `Basic ${Buffer.from(`${config.public_key}:${config.secret_key}`).toString("base64")}`;
  return { base, request: (path, options = {}) => fetch(`${base}${path}`, {
    ...options,
    redirect: "error",
    signal: AbortSignal.timeout(15e3),
    headers: { ...options.headers, Authorization: auth }
  }) };
}
async function connectLangfuse(settings) {
  const config = langfuseConfig(settings);
  const response = await config.request("/api/public/projects");
  if (!response.ok) throw new Error(`Langfuse project authentication failed (HTTP ${response.status}).`);
  const projects = (await response.json()).data;
  if (projects?.length !== 1 || !projects[0].id) throw new Error("Use API keys for exactly one Langfuse project.");
  return { ...config, project: projects[0], target: `${config.base}/${projects[0].id}` };
}

// scripts/content.mjs
var privateKey = /^(?:reasoning(?:_content)?|thinking|signature|authorization|password|secret|api[_-]?key|access[_-]?token|refresh[_-]?token)$/i;
function redact(text) {
  return text.replace(/<(?:think|thinking|analysis)\b[^>]*>[\s\S]*?<\/(?:think|thinking|analysis)>/gi, "[reasoning omitted]").replace(/\b(?:sk-(?:lf-)?[\w-]{8,}|Bearer\s+[\w.\/-]{8,})/g, "[REDACTED]").replace(/((?:api[_-]?key|password|secret|access[_-]?token)\s*[=:]\s*["']?)[^\s"',;]+/gi, "$1[REDACTED]").replace(/-----BEGIN [^-]*PRIVATE KEY-----[\s\S]*?-----END [^-]*PRIVATE KEY-----/g, "[PRIVATE KEY OMITTED]").replace(/\/(?:Users|home)\/[^/\s"']+/g, "[HOME]");
}
function sanitizeContent(value, maxChars = 16e3) {
  let redacted = false;
  const clean = (item, depth = 0) => {
    if (depth > 20) {
      redacted = true;
      return "[depth limit]";
    }
    if (typeof item === "string") {
      const text2 = redact(item);
      redacted ||= text2 !== item;
      return text2;
    }
    if (Array.isArray(item)) return item.map((child) => clean(child, depth + 1));
    if (item && typeof item === "object") return Object.fromEntries(Object.entries(item).map(([key, child]) => {
      if (privateKey.test(key)) {
        redacted = true;
        return [key, "[REDACTED]"];
      }
      return [key, clean(child, depth + 1)];
    }));
    return item;
  };
  const cleaned = clean(value);
  const text = typeof cleaned === "string" ? cleaned : JSON.stringify(cleaned);
  if (text === void 0) return { value: null, redacted, truncated: false };
  const truncated = text.length > maxChars;
  return {
    value: truncated ? `${text.slice(0, maxChars)}
[truncated]` : cleaned,
    redacted,
    truncated,
    ...truncated ? { originalChars: text.length } : {}
  };
}

// scripts/entry.mjs
import { realpathSync } from "node:fs";
import { fileURLToPath as fileURLToPath2 } from "node:url";
function isMain(url) {
  try {
    return !!process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath2(url));
  } catch {
    return false;
  }
}

// plugins/codex-langfuse/scripts/hook.mjs
var turnKey = (turn) => turn.turnId || String(turn.startTime);
async function readRollout(file) {
  const lines = [];
  const text = await readFile(file, "utf8"), raw = text.split("\n");
  for (const [index, line] of raw.entries()) {
    if (!line.trim()) continue;
    try {
      lines.push(JSON.parse(line));
    } catch {
      if (index !== raw.length - 1 || text.endsWith("\n")) throw new Error("Rollout contains a malformed complete line. Export stopped.");
    }
  }
  const parsed = parseSession(lines);
  if (!parsed.sessionMeta.sessionId || parsed.sessionMeta.sessionId === "unknown") throw new Error("Rollout has no session identity.");
  return parsed;
}
async function findChild(parent, id) {
  if (!/^[a-zA-Z0-9_-]+$/.test(id)) throw new Error("Invalid subagent identity.");
  const root = resolve2(dirname3(parent), "../../..");
  if (basename(root) !== "sessions") throw new Error("Subagent lookup requires the Codex sessions/YYYY/MM/DD layout.");
  async function walk(dir) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const file = join3(dir, entry.name);
      if (entry.isDirectory()) {
        const found = await walk(file);
        if (found) return found;
      } else if (entry.isFile() && entry.name.endsWith(`-${id}.jsonl`)) return file;
    }
  }
  return walk(root);
}
function usageDetails(usage) {
  if (!usage) return;
  const { input_tokens: input, output_tokens: output, total_tokens: total, cached_input_tokens: cached = 0, reasoning_output_tokens: reasoning = 0 } = usage;
  if (![input, output, total, cached, reasoning].every((n) => Number.isSafeInteger(n) && n >= 0) || total !== input + output || cached > input || reasoning > output) return;
  return { input: input - cached, input_cached: cached, output: output - reasoning, output_reasoning: reasoning };
}
function attribute(key, value) {
  return { key, value: typeof value === "boolean" ? { boolValue: value } : typeof value === "number" ? { intValue: String(value) } : { stringValue: typeof value === "string" ? value : JSON.stringify(value) } };
}
async function recordsForTurn(file, parsed, turn, config) {
  const records = [], traceId = digest(`langfuse-helper:codex:${parsed.sessionMeta.sessionId}:${turnKey(turn)}`).slice(0, 32);
  const sessionId = `codex:${parsed.sessionMeta.sessionId}`, seen = /* @__PURE__ */ new Set();
  const content = (value) => config.content === "text" && value !== void 0 ? JSON.stringify(sanitizeContent(value, config.maxContentChars).value) : void 0;
  const add = (key, name, type, start, end, parent, fields = {}) => {
    if (!Number.isFinite(start) || !Number.isFinite(end) || end < start) throw new Error("Invalid observation timestamps.");
    const spanId = digest(`${traceId}:${key}`).slice(0, 16);
    const attrs = {
      "langfuse.session.id": sessionId,
      "langfuse.trace.name": "Codex",
      "langfuse.observation.type": type,
      "langfuse.observation.metadata.agent": "codex",
      "langfuse.observation.metadata.contentMode": config.content,
      "langfuse.observation.metadata.source": "codex-rollout",
      ...fields
    };
    const span = {
      traceId,
      spanId,
      ...parent ? { parentSpanId: parent } : {},
      name,
      startTimeUnixNano: String(BigInt(Math.trunc(start)) * 1000000n),
      endTimeUnixNano: String(BigInt(Math.trunc(end)) * 1000000n),
      attributes: Object.entries(attrs).filter(([, v]) => v !== void 0).map(([k, v]) => attribute(k, v))
    };
    span.attributes.push({ key: "langfuse.trace.tags", value: { arrayValue: { values: [{ stringValue: "codex" }] } } });
    const payload = { resourceSpans: [{ resource: { attributes: [attribute("service.name", "langfuse-helper-codex")] }, scopeSpans: [{ scope: { name: "langfuse-helper" }, spans: [span] }] }] };
    records.push({ key: `${traceId}:${spanId}`, digest: digest(JSON.stringify(payload)), payload });
    return spanId;
  };
  async function emit(currentFile, session, current, parent) {
    if (!current.completed) throw new Error("Waiting for a complete turn and subagent tree. Retry after completion.");
    const key = `${session.sessionMeta.sessionId}:${turnKey(current)}`;
    if (seen.has(key)) throw new Error("Repeated subagent reference. Export stopped.");
    seen.add(key);
    const root = add(key, parent ? "Codex Subagent Turn" : "Codex Turn", "agent", current.startTime, current.endTime, parent, {
      "langfuse.observation.metadata.threadId": session.sessionMeta.sessionId,
      "langfuse.observation.metadata.turnId": turnKey(current),
      "langfuse.observation.metadata.aborted": current.aborted,
      "langfuse.observation.level": current.aborted ? "WARNING" : "DEFAULT",
      "langfuse.observation.input": content(current.userInput),
      "langfuse.observation.output": content(current.finalOutput)
    });
    for (const [i, step] of current.steps.entries()) {
      const generation = add(`${key}:step:${i}`, "LLM", "generation", step.startTime, step.endTime, root, {
        "langfuse.observation.model.name": current.model,
        "langfuse.observation.usage_details": usageDetails(step.usage),
        "langfuse.observation.input": i === 0 ? content(current.userInput) : void 0,
        "langfuse.observation.output": content(step.text)
      });
      for (const [j, tool] of step.toolCalls.entries()) add(
        `${key}:step:${i}:tool:${tool.callId || j}`,
        tool.mcp ? `${tool.mcp.server}.${tool.mcp.tool}` : tool.name || "tool",
        "tool",
        tool.startTime,
        tool.endTime ?? step.endTime,
        generation,
        {
          "langfuse.observation.metadata.callId": tool.callId,
          "langfuse.observation.level": tool.error ? "ERROR" : "DEFAULT",
          "langfuse.observation.input": content(tool.args),
          "langfuse.observation.output": content(tool.output)
        }
      );
    }
    for (const id of current.subagentThreadIds) {
      const childFile = await findChild(currentFile, id);
      if (!childFile) throw new Error("A subagent rollout is not available yet. Retry after completion.");
      const child = await readRollout(childFile);
      if (!child.turns.length) throw new Error("Waiting for subagent turns.");
      for (const childTurn of child.turns) await emit(childFile, child, childTurn, root);
    }
  }
  await emit(file, parsed, turn);
  return records;
}
async function waitForCompletedTurn(input, { timeoutMs = 6e4, pollIntervalMs = 100 } = {}) {
  const deadline = Date.now() + timeoutMs, key = input.waitTurn || input.turn_id;
  if (!key) throw new Error("The deferred capture is missing its turn identity.");
  while (true) {
    if (!readProfiles().agents.codex?.enabled) return;
    const parsed = await readRollout(input.transcript_path);
    if (parsed.turns.some((turn) => turnKey(turn) === key && turn.completed)) return;
    if (Date.now() >= deadline) throw new Error("Timed out waiting for Codex to persist the completed turn. Retry with codex export after completion.");
    await delay(pollIntervalMs);
  }
}
async function capture(input, { send = true, defer = false } = {}) {
  if (!readProfiles().agents.codex?.enabled) return { enabled: false, uploaded: 0 };
  const config = resolveAgent("codex");
  if (!input.transcript_path) throw new Error("Hook payload is missing transcript_path.");
  const parsed = await readRollout(input.transcript_path);
  if (input.session_id && input.session_id !== parsed.sessionMeta.sessionId) throw new Error("Hook session and rollout identity differ.");
  if (parsed.sessionMeta.isSubagentThread) return { uploaded: 0, reason: "Subagent is exported through its parent." };
  const bindingPath = join3(helperHome(), "bindings/codex", `${digest(parsed.sessionMeta.sessionId)}.json`);
  let binding = readJson(bindingPath, null);
  if (binding && binding.identity !== config.identity) throw new Error("This task belongs to a different target. Start a new Codex task, or select its original target.");
  if (!binding) {
    const first = input.turn_id ? parsed.turns.find((turn) => turn.turnId === input.turn_id) : defer ? parsed.turns.at(-1) : parsed.turns.findLast((turn) => turn.completed);
    if (!first) throw new Error("The completed hook turn is not available in the rollout yet.");
    binding = { identity: config.identity, first: turnKey(first), content: config.content, maxContentChars: config.maxContentChars };
    if (send) {
      mkdirSync2(dirname3(bindingPath), { recursive: true, mode: 448 });
      try {
        writeFileSync2(bindingPath, JSON.stringify(binding), { mode: 384, flag: "wx" });
      } catch (error) {
        if (error.code !== "EEXIST") throw error;
        binding = readJson(bindingPath, null);
      }
      if (!binding || binding.identity !== config.identity) throw new Error("Task target changed during capture. Start a new task.");
    }
  }
  const firstIndex = parsed.turns.findIndex((turn) => turnKey(turn) === binding.first);
  if (firstIndex < 0) throw new Error("The original capture boundary is missing. Export stopped.");
  if (defer) {
    const turn = input.turn_id ? parsed.turns.find((turn2) => turn2.turnId === input.turn_id) : parsed.turns.at(-1);
    if (!turn) throw new Error("The hook turn is not available in the rollout yet.");
    const status = { enabled: true, phase: "waiting-for-turn-complete", turnId: turnKey(turn), target: config.targetName, updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
    saveJson(join3(config.data_directory, "status.json"), status);
    const child = spawn(process.execPath, [fileURLToPath3(import.meta.url), "--after-stop"], {
      detached: true,
      stdio: ["pipe", "ignore", "ignore"]
    });
    await new Promise((resolve3, reject) => {
      child.once("error", reject);
      child.stdin.once("error", reject);
      child.stdin.end(JSON.stringify({ ...input, waitTurn: turnKey(turn) }), resolve3);
    });
    child.unref();
    return status;
  }
  if (input.turn_id && !parsed.turns.find((turn) => turn.turnId === input.turn_id)?.completed) {
    throw new Error("The hook turn is not complete in the rollout yet. Retry after completion.");
  }
  const settings = { ...config, content: binding.content, maxContentChars: binding.maxContentChars };
  const selected = parsed.turns.slice(firstIndex).filter((turn) => turn.completed);
  if (!send) {
    const records = [];
    for (const turn of selected) records.push(...await recordsForTurn(input.transcript_path, parsed, turn, settings));
    return { mode: "preview", sessionId: parsed.sessionMeta.sessionId, target: config.targetName, turns: selected.length, observations: records.length, content: settings.content };
  }
  const connected = await connectLangfuse(config);
  if (connected.target !== config.identity) throw new Error("API keys now resolve to another project. Configure a new target.");
  mkdirSync2(config.data_directory, { recursive: true, mode: 448 });
  const ledger = new DeliveryLedger(join3(config.data_directory, "langfuse-deliveries.sqlite"), config.identity);
  const completedPath = join3(config.data_directory, "turns", `${digest(parsed.sessionMeta.sessionId)}.json`);
  const completed = new Set(readJson(completedPath, []));
  let uploaded = 0;
  try {
    for (const turn of selected) {
      if (completed.has(turnKey(turn))) continue;
      const records = await recordsForTurn(input.transcript_path, parsed, turn, settings);
      let batch = [], bytes = 0;
      const flush = async () => {
        uploaded += await sendRecords(batch, ledger, (body) => connected.request("/api/public/otel/v1/traces", {
          method: "POST",
          headers: { "Content-Type": "application/json", "x-langfuse-ingestion-version": "4" },
          body
        }));
        batch = [];
        bytes = 0;
      };
      for (const record of records) {
        const size = Buffer.byteLength(JSON.stringify(record.payload));
        if (batch.length && (batch.length >= 100 || bytes + size > 3 * 1024 * 1024)) await flush();
        batch.push(record);
        bytes += size;
      }
      if (batch.length) await flush();
      completed.add(turnKey(turn));
      saveJson(completedPath, [...completed]);
    }
    const status = { enabled: true, uploaded, deliveries: ledger.counts(), lastSuccess: (/* @__PURE__ */ new Date()).toISOString(), target: config.targetName };
    saveJson(join3(config.data_directory, "status.json"), status);
    return status;
  } finally {
    ledger.close();
  }
}
if (isMain(import.meta.url)) {
  try {
    let text = "";
    for await (const chunk of process.stdin) text += chunk;
    const input = JSON.parse(text), afterStop = process.argv.includes("--after-stop");
    if (afterStop) await waitForCompletedTurn(input);
    const result = await capture(input, {
      send: !process.argv.includes("--preview"),
      defer: !afterStop && !process.argv.includes("--report") && !process.argv.includes("--preview")
    });
    if (process.argv.includes("--report")) console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    try {
      saveJson(join3(resolveAgent("codex").data_directory, "status.json"), { lastFailure: (/* @__PURE__ */ new Date()).toISOString(), error: error.message });
    } catch {
    }
    if (process.argv.includes("--report")) {
      console.error(error.message);
      process.exitCode = 1;
    } else console.error("Langfuse Helper could not complete delivery. Run langfuse-helper codex status.");
  }
}
export {
  capture,
  parseSession,
  readRollout,
  recordsForTurn,
  waitForCompletedTurn
};
