import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

await build({
  absWorkingDir: fileURLToPath(new URL('../', import.meta.url)),
  entryPoints: ['plugins/codex-langfuse/scripts/hook.mjs'],
  outfile: 'plugins/codex-langfuse/runtime/hook.mjs',
  bundle: true, platform: 'node', target: 'node24', format: 'esm',
  banner: { js: '// Generated by npm run build. Includes MIT-licensed Langfuse rollout parsing; see ../vendor/LICENSE and ../UPSTREAM.md.' },
});
